### ISSUE TITLE
AI shooting thru object.

### ISSUE THREAD

**Issue by Metalica** [genesis92x/VCOMAI#8]
**Problem:**
AI is shooting thru object, like rock or wall.
**How to fix:**
AI should understand, that there is obstacle and try to shoot above it.

**Comment by genesis92x** [comment]
Unfortunately this occurs in many situations. Mostly when AI are in a building their rifle can clip through the wall and shoot players. I'm not aware of an efficient way to resolve this issue, besides adding in costly visibility checks from an AI's eyes to their target. To help mitigate these issues AI need to be set into the standing animation when inside buildings or near thin walls.

**Comment by Metalica** [comment]
Understand.
